# Introduction

The increasing rate of global warming over the Southern African region has resulted in continuous experience of climate variability. In congruence with studies done by the Intergovernmental Panel on Climate Change (IPCC 2014) and scenarios projected by the Lesotho Meteorological Services (LMS 2017), climate change is already affecting Lesotho’s climatic patterns with resultant substantial environmental and socio-economic loss, particularly because of its mountainous topography and socio-economic conditions.
According to Lesotho Meteorological Services (LMS 2017) rainfall is highly variable both temporally and spatially, thus droughts and floods are common occurrences. High intensity rainfall often produces flash floods that accelerate soil erosion leading to high sediment loads in rivers. Snowfall occurs annually over the mountains and on average once every three years in the lowlands causing serious problems, not only resulting in extremely low temperatures but in restrictions on movement and access to essential services as well as the mountain communities including loss of livestock. Strong winds are common, causing destruction of infrastructure such as houses and power lines .Droughts alone are estimated to reduce total GDP by 1% - 4%, while soil erosion (40 million tons lost per year) has been estimated to reduce agricultural GDP by 2%-3% (around 1% of total GDP) (LMS 2000, LMS 2017). 
Lesotho’s population is made up of one homogeneous ethnic grouping (Basotho), and is estimated to be 2 million with ran estimation of 80% of the population reside in rural areas (FAO 2018). A significant portion (49.2%) of the population in Lesotho lives under the poverty line which makes them more vulnerable to climate change since they do not have sufficient incomes to prepare and protect themselves from the adverse effects of climate change (UNDP 2020). This means that the majority of Lesotho’s population does not have adequate adaptive capacity and resilience to climate change.
 In an effort to bring transformational change in country’s capacity to address the impacts of climate change the nation has adopted a number of strategic instruments such as the National Strategic Resilience Framework (2017-2030) and Climate Change policy (2017 – 2027) and National Early Warning Strategic Action Plan, (2020). However, despite initiatives taken towards being more resilient to natural hazards and in reducing disaster risk, climate change is posing real time and potential challenges to the country’s natural resources dependent livelihoods (Draft National Disaster Risk Management Strategy and Action Plan 2020). Therefore, integrating climate change information into development planning and decision making can improve adaptive capacity and resilience. There is a need for powerful adaptation policies and programmes with implementing capacity across all systems.   
It is widely agreed that adaptation strategies (Cancun Adaptation Framework (2010), World Economic Forum Davos  2020) could fuel reduction in harmful effects of climate change  in the Least Developed Countries such as Lesotho. Sustainability in adaptation interventions will translate to contextually socio-economically and environmentally feasible development pathways. Countries stand to lose the hard won sustainable development gains if they do not build the resilience of people, places, ecosystems, and economies to the impacts of climate change. Therefore, the NAP process is highly essential for Lesotho given the prevailing  climate change related challenges that are facing the country, and which are clear and detrimental impacts on its people, ecosystems and economy. 
During the launch of the NAP Lesotho (2015), it was strongly emphasised that the NAP process will help to identify a NAP roadmap for Lesotho, facilitating the coordination of all the existing adaptation projects and initiatives, and the formulation of new concepts which will be further developed into bankable projects to reduce vulnerability, build capacity and mainstream adaptation into all systems and sectors specific development plans. NAP will clearly identify and prioritise the key adaptation measures required to address the country’s peculiar adaptation needs, and the processes to ensure that these measures are mainstreamed into the national planning and development processes and programmes across systems and sectors. 
The Lesotho National Climate Change Policy (2017-2027) sets the basis for addressing one of its core pillars, “adaptation and climate risk reduction”, noting that adaptation to climate change is of utmost importance to ensure socio-economic and environmental systems function and development, and to avoid loss and damage. It points out that adaptation in sectors such as water, agriculture and food systems, early warning, energy, land use, health and biodiversity, among others, are key to paving the way to a climate resilient pathway. 
Prior to the initiative on NAP development, Lesotho developed a number of documents and programmes in relation to adaptation interventions. The documents include the NAPA (2007) and  NDC (2015). However, with the NAPA gaps were identified and these are sectoral and zone based (concentration in southern districts of Lesotho) characterised with fragmental approaches (different implementing strategies from individually implementing entities) which poses a high probability for maladaptation.  Moreover, it had limitations in terms of trans- regional adaptation capacity and multi sectoral connectivity in a long term timeframe. Therefore, the NAP process will address these shortfalls identified and work towards a more systematic approach with interconnectedness within bio-physical and socio economic development spheres. Consequently, the experience potentially leverages Lesotho in a good position to develop the NAP process. 
Therefore, in the NAP process Lesotho  adopts a “systems” rather than “sectoral” approach as it provides a more integrative and holistic understanding that better underpins required and effective adaptation strategies. While the National Adaptation Programme of Action( 2007) identified the country’s “urgent and immediate” priority needs for adaptation, the NAP process extends this to cover adaptation measures that the country needs to focus on for its medium- and long-term priorities for adapting to climate change and defines clear actions to develop the necessary capacities and systems and to operationalise necessary actions needed to make adaptation an integral part of a country’s development planning, decision making and budgeting. 



