# Framework for the NAP

Lesotho’s geographical characteristics and prevailing socioeconomic conditions among the majority of its rural population make it one of the most vulnerable countries to the impacts of climate change . Climate change is affecting Lesotho in many ways. Recurrent and devastating droughts and high temperatures cause food insecurity which affects hundreds of thousands of people through reduced agricultural yields as a consequence of low soil moisture, higher livestock mortality, increased food prices for both human and livestock consumption, and reduction in the effectiveness of traditional farming practices. Drought lowers hydroelectric power production and increases water insecurity particularly in the lowlands where about two-thirds of the national population reside. 

The effects of the droughts are compounded by degraded soils, rangelands and wetlands, decreasing availability of agricultural land, reduced availability and quality of potable water for humans, livestock and wildlife, and biome shifts. Higher temperatures are increasing human and livestock susceptibility to heat stress, exacerbating the incidences of pests and diseases, and contributing to crop failures through crop wilting. On the other hand, intense rainfall and runoff, floods, hail and heavy snowfalls destroy crops and infrastructure such as roads, bridges and power lines, enhance soil erosion and land degradation which result in turbid rivers and compromised ecosystem services, and increase susceptibility to water-borne diseases. Both droughts and floods directly result in loss of human lives, and also kill livestock and wildlife. Increasing rainfall variability, shorter rainfall seasons and late onset of rainy seasons contribute to reduced crop and pasture yields, unreliable water supply and hydropower generation, reduced availability of groundwater due to inadequate recharge, and more broadly to degraded ecosystem services. All these changes, among others, are depressing economic activities, with significant impact on national GDP, and diminishing the wellbeing particularly of the large population of rural dwellers whose livelihoods depend on the rangelands, wetlands, indigenous plant and animal species, and ecotourism, as well as the urban poor who contend with unemployment and inequality.

The National Adaptation Planning process which was initiated during the seventeenth session of the Conference of the Parties (COP) to the United Nations Framework Convention on Climate Change (UNFCCC) is today an essential component of planning at all levels because climate change is an issue that has to be addressed over the long-term. The process enables developing and least developed country (LDC) parties to assess their vulnerabilities, mainstream climate change risks, and to address adaptation across all key sectors that are impacted by climate change (LEG, 2012). Further, it is essential that developing country and LDC parties integrate adaptation planning in the broader context of sustainable development planning  because climate change risks disproportionately magnify development challenges in these countries as compared to developed countries (LEG, 2012). The national adaptation plan (NAP) process was, therefore, established by the COP as a pathway by which effective adaptation planning in LDCs and other developing countries can be facilitated. The Government of Lesotho embarked upon the National Adaptation Plan (NAP) process to adopt a medium-term approach for reducing vulnerability to climate change impacts, and to facilitate the integration of climate change adaptation into ongoing planning processes at national and subnational levels.


The agreed objectives of the national adaptation plan process are (LDC-EG, 2012): (a) To reduce vulnerability to the impacts of climate change, by building adaptive capacity and resilience; (b) To facilitate the integration of climate change adaptation, in a coherent manner, into relevant new and existing policies, programmes and activities, in particular development planning processes and strategies, within all relevant sectors and at different levels, as appropriate. 

The implementation of the NAP process is intended to:  

*	build on existing CCA planning processes and initiatives in order to provide continuity with previous planning efforts;
*	build on past implementation successes;
*	eliminate duplication of effort; and
*	avoid repetition of implementation failures. 


##	Essential functions of the NAP process

The NAP for Lesotho will serve the following functions:

1.	Provide a pivotal framework for mainstreaming and coordination of adaptation efforts at national and sub-national levels and across systems and sectors in support of the core pillar “adaptation and climate risk reduction” as outlined in the National Climate Change Policy 2017-2027, and to interface with regional and international mechanisms.
2.	Support adaptation planning and implementation at all levels through the collection, compilation, processing and dissemination of data, information and knowledge on climate change and national development. The various government agencies will contribute to this effort through their respective mandates and in association with local and international development partners including the private sector.
3.	Identify and address capacity gaps and needs to ensure that adaptation strategies are properly designed and implemented.
4.	Assess climate-development linkages and needs to support the integration of climate change adaptation into national and sub-national development and sectoral planning and in support of the 22 policy statements in the National Climate Change Policy.
5.	Provide analyses of national and sub-national climate data, assess vulnerabilities to climate change, and identify appropriate adaptation options at scale. This will require the cooperation of all devolved units of governance down to the community and urban councils and coordination to ensure that the different data streams are in standardised formats that allows for integration and comparison. The NAP secretariat would provide these standards.
6.	Support decision-making on adaptation investments and development planning through appraisals of adaptation options.
7.	Promote and facilitate the prioritisation of climate change adaptation in national planning.
8.	Facilitate the implementation of adaptation at all levels through its mainstreaming into policies, projects and programmes and to maximise on synergies.
9.	Provide a framework for monitoring, review and updating of adaptation plans over time, ensure progress and effectiveness of adaptation efforts, and outline how gaps are being addressed.
10.	Coordinate reporting and outreach on the NAP process to national and international stakeholders and formally on progress to the UNFCCC.


##	The NAP as the umbrella programme for adaptation

There are several development programmes and activities that are taking place in Lesotho at national and sub-national levels under national government ministries and parastatals or through bilateral arrangements and partnerships with private sector entities, which need to be buttressed to be resilient to the impacts of climate changes in order to be able to effectively contribute to targeted development outcomes. Among many others, these include: Ministry of Finance “Millennium Challenge Account Lesotho Project” which has implemented projects in urban and rural water supplies and health and now targets a second phase focusing on health, job skills, land, and the regulatory environment; Ministry of Energy and Meteorology “Sustainable Energy for All” project from household to national level and across rural and urban areas; Ministry of Water – has several ongoing projects such as the Lesotho Water Sector Improvement Phase II to supply water to the Lowlands (Maseru,  Roma, Morija, Mazenod, Teyateyaneng) and stand-alone solutions to villages; Ministry of Health – Lesotho Nutrition and Health System Strengthening Project, which recognises climate change but does not tie in its impacts to its health services delivery, and; several programmes implemented bilaterally between the government and international donor or investment agencies. 

The Ministry of Social Development is implementing the Community Development Model as a sustainable intervention to build the capacities of communities to graduate from poverty and social assistance programs through livelihoods establishment, though this effort is constrained by financial resources which could potentially be leveraged through linking with livelihoods-related projects that are under different ministries and programmes. The Climate Finance Facility Project seeks to crowd in private sector investment by de-risking and increasing the bankability of climate projects. Further, while the country is committed to ensuring full and productive employment and decent work for all including women, youth and people with disabilities, climate impacts on its various systems are undermining the efforts to achieve these objectives (Lesotho VNR 2019). However, the involvement of these different actors and the private sector, are sector- and project-constrained, and gendered aspects are not clearly staged. 

Given its cross-cutting nature which includes, inter alia, considerations of adaptive capacity and resilience at systems level while considering also the individual, institutional, and systemic factors, and its mainstreaming into governance and development planning structures, the NAP offers an appropriate umbrella under which national programmes for adaptation can be jointly framed, coordinated and implemented. The NAP will present an aggregate national adaptation plan that will link to appropriate local, subnational, national, and sectoral activities and action plans, maximise on efficiencies, minimise duplication of efforts, and leverage on cost constraints to programme implementation. The NAP process shall also add value to past and current activities by identifying capacity gaps, especially for the design and implementation of medium-term climate change adaptation priorities, as well as by accessing opportunities for international funding to develop more effective climate responsive planning and budgeting. The Lesotho NAP coalesces all the discrete climate change adaptation plans and programmes that are or shall be implemented in the country. It comprises of collated, synthesised and analysed data of climate change trends and its impacts, aggregated from local level and downscaled from regional analyses, as well as related peculiar vulnerabilities at scale within and across regions and systems, and identifies gaps and capacity needs that should be addressed. This information will be used to identify and prioritise adaptation options, and to put in place plans to implement the proposed adaptation options, as well as how to finance them. Finally, a monitoring and evaluation framework is determined for the different programmes to track progress and to make adjustments where necessary. Periodic updates (every four years) shall be undertaken to ensure that the NAP is responsive to new and emerging needs and offers an effective mechanism for climate change adaptation at scale. 


##	Coherence with national development context, SDGs, Sendai and other relevant frameworks

The Lesotho Vision 2020  which was adopted in 2004 is anchored on seven pillars of development, namely; democracy, unity, peace, education and training, economic growth, management of the environment, and advancement in technology. It recognized that “poor land use management as well as climate change and a general degradation of the environment have led to aridity and barrenness of the land with an unmistakable signs of the onset of desertification”. The vision statement highlights a “healthy and well-developed human resource base”, a “strong economy”, a “well-managed environment”, and “well-established technology” which all broadly speak to the goals of the NAP process as well. The Coalition Agreement of 2015 outlines 12 specific commitments, of which 7 are directly pertinent to climate change adaptation and resilience building, and these include: growing the economy faster through…effective use of natural resources, infrastructure development and retaining within the country a greater proportions of earnings from natural resources (B1); enhancing the strategic management of natural resources through creating a Ministry of Water (B2); growing the private sector and promoting the tourism industry (B4); promoting food security and commercial agriculture (B5); supporting Small, Micro and Medium Enterprises (SMMEs) through appropriate regulatory policies and access to finance (B6); reducing poverty and inequality, and improving access to effective social services for its citizens (B8) and; addressing the needs of vulnerable populations including orphans, children, young people, women, the elderly and people with disabilities (B9). 

Lesotho developed the National Climate Change Policy 2017-2027, providing the basis for the development of other national strategies and plans. For example, the National Strategic Development Plan (NSDP II) 2018/19-2022/23 recognizes that climate change is a challenge that needs to be responded to in a strategic manner using appropriate approaches because it contributes to lower land quality, heightens extreme weather conditions (e.g. recurrent droughts, heavy rain falls and floods, strong winds, early/late frosts, hail, snow storms) which sometimes lead to emergency relief efforts that divert much needed finances from development projects, and has significant adverse consequences for agriculture, food security, poverty and vulnerability. It is viewed as “the greatest threat to Lesotho’s developmental progress” . The NSDP II, which is also aligned with the African Union Agenda 2063 and Regional Indicative Strategic Development Plan, is implementing the final years of the goals set out in Vision 2020, and also operationalizes the Sustainable Development Goals (SDG) 2030 agenda. On the other hand, the National Resilience Strategic Framework  2017-2030 and the Disaster Risk Management Bill 2020 aligns with the Sendai Framework. Lesotho is therefore well placed to enact and mainstream a NAP to operationalize its approach to adaptation to climate change and to monitor progress towards desired outcomes.

