# Vision, goals and objectives of the NAP

## Vision for Adaptation for the Country


The vision is to have a well-adapted Lesotho that achieves its medium to long-term sustainable development objectives in the context of a changing climate. 

## Goals and Objectives of the NAP
The main goals and objectives of the Lesotho NAP, in line with the National Climate Change Policy, are:
Goals  

*	Reverse environmental degradation and adapt to climate change 
*	All stakeholders address climate change impacts and their causes through the identification, mainstreaming and implementation of appropriate adaptation and mitigation measures, while promoting sustainable development. 
Objectives
*	Promote climate-resilient, social, economic and environmental development that is compatible with, and mainstreamed into, national development planning and national budget-setting processes;
*	Explore low-carbon development opportunities, nationally and internationally, in order to promote
the sustainable use of resources and
*	Strengthen a framework that promotes efficient climate change governance, strong international cooperation, capacity building, research and systematic observations, clean technology development, transfer and use, education, training and public awareness and financing in a way that also benefits the most vulnerable through the implementation arrangements to be defined in the NAP.

